# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Service First at Service Drug
email: mail@servicedrug.net
description: > # this means to ignore newlines until "baseurl:"
  Service Drug has served the citizens of Millard County since 1939. 
  As a locally owned and operated pharmacy, the staffs in Delta and 
  Fillmore are able to address customer needs in a unique way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://servicedrug.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude: [less, .bower.json, .gitignore, CHANGELOG.md, fonts, grunt, Gruntfile.js, LICENSE, node_modules, nuget, package.js, package.json, README.md]
